import { Link } from "@/i18n/navigation";
import { studioServices } from "@/lib/studio-services";
import type { Locale } from "@/i18n/routing";
import { getTranslations } from "next-intl/server";
import {contactHref} from "@/lib/contact";
import MaterialStudy from "./MaterialStudy";

type Props = {locale: Locale; base?: string};
export function SiteCTA({locale,intent}: {locale:Locale;base:string;intent?:string}) {const ar=locale==="ar";return <section className="dir-page-cta dir-container"><h2>{ar?"نبدأ باللي في بالك.":"Let's start with what you know."}</h2><a className="dir-button" href={contactHref(locale,intent)}>{ar?"احكِ لنا فكرتك":"Tell us your idea"}<span aria-hidden>↗</span></a><p>{ar?"مو لازم تكون كل التفاصيل واضحة من البداية.":"You don't need to have it all figured out."}</p></section>;}
export function SiteServices({locale,base=""}:Props) {
 const ar=locale==="ar";return <><section className="dir-page-hero dir-container"><div><h1>{ar?"المشكلة أولًا.\nثم ما تحتاجه.":"The right work.\nFor your next step."}</h1><p>{ar?"موقع أو تطبيق أو طريقة عمل أسهل. نختار الأدوات والتخصصات حسب ما يحتاجه مشروعك.":"A website, an app, or an easier way of working. The mix of disciplines follows what your project needs."}</p></div><MaterialStudy form="website"/></section><section className="dir-services-list dir-container" aria-label={ar?"الخدمات":"Services"}>{studioServices[locale].map((s,i)=><article key={s.slug} data-mosaic-card><span className="dir-service-number">0{i+1}</span><div><h2><Link href={`${base}/services/${s.slug}`}>{s.title}<span aria-hidden>↗</span></Link></h2><p>{s.summary}</p></div><ul>{s.outputs.map(o=><li key={o}>{o}</li>)}</ul><Link className="dir-inline-link" href={`${base}/services/${s.slug}`} aria-label={`${ar?"اكتشف":"Explore"} ${s.title}`}>{ar?"التفاصيل":"Explore"} ↗</Link></article>)}</section><SiteCTA locale={locale} base={base}/></>;
}
export function SiteService({locale,base="",slug}:Props & {slug:string}) {
 const ar=locale==="ar", s=studioServices[locale].find(s=>s.slug===slug)!;
 return <><section className="dir-page-hero dir-container"><div><Link className="dir-breadcrumb" href={base+"/services"}><span aria-hidden="true">←</span> {ar?"كل الخدمات":"All capabilities"}</Link><h1>{s.title}</h1><p>{s.summary}</p><a className="dir-button" href={contactHref(locale,s.intent)}>{ar?"لنناقش مشروعك":"Let's discuss your project"}<span aria-hidden>↗</span></a></div><MaterialStudy form={s.intent === "ai" ? "workflow" : slug === "product-engineering" ? "website" : "product"}/></section><section className="dir-service-intro dir-container"><h2>{s.situation}</h2><p>{s.intro}</p></section><section className="dir-service-work dir-container"><div><div className="dir-work-list">{s.work.map(([title,body],i)=><article key={title}><span>0{i+1}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</div></div><aside className="dir-outputs">{<h3 className="mx-aside-title">{ar?"ما نجهّزه معك":"What we’ll make together"}</h3>}<ul>{s.outputs.map(o=><li key={o}><span aria-hidden>↗</span>{o}</li>)}</ul><p>{ar?"نتفق على نطاق العمل والتسليمات قبل البداية.":"Scope and deliverables are agreed before work begins."}</p></aside></section><section className="dir-related dir-container"><h2>{ar?"تخصصات تكمل الصورة":"Part of the bigger picture"}</h2>{studioServices[locale].filter(x=>x.slug!==slug).slice(0,2).map(x=><Link key={x.slug} href={`${base}/services/${x.slug}`}>{x.title}<span aria-hidden>↗</span></Link>)}</section><SiteCTA locale={locale} base={base} intent={s.intent}/></>;
}
export function SiteAbout({locale,base=""}:Props) {
 const ar=locale==="ar"; const principles=ar?[
 ["نبدأ بالناس.","مين يستخدم المنتج؟ وش يحتاج ينجز؟ هذه الأسئلة تسبق اختيار الأدوات وقائمة المزايا."],
 ["نجعل الفكرة قابلة للتجربة.","نموذج تتفاعل معه، خطوات تراجعها، وقرارات نفهم أسبابها معًا. تظل جزءًا من رحلة العمل."],
 ["نهتم بما يحدث بعد أول انطباع.","التحميل، الأخطاء، الجوال والعربية. تفاصيل الاستخدام اليومي جزء من جودة المنتج."]
 ]:[
 ["People before the feature list.","Who will use it? What do they need to get done? These questions come before the tools and the feature list."],
 ["Make the idea tangible.","A prototype to try, progress to review, and decisions you can understand. You stay part of the work."],
 ["Care beyond the first impression.","Loading, errors, mobile and Arabic. The everyday details are part of the product, not an afterthought."]
 ];return <><section className="dir-page-hero dir-container"><div><h1>{ar?"قريبون من الناس.\nجادّون في الصنعة.":"Human by nature.\nCareful by design."}</h1><p>{ar?"ميوز استوديو سعودي يجمع التفكير بالمنتج والتصميم والتطوير. نبني للأعمال ونطوّر أفكارنا الخاصة.":"Muse is a Saudi studio bringing product thinking, design and engineering together. We build for businesses while developing ideas of our own."}</p></div><MaterialStudy /></section><section className="dir-about-statement dir-container"><h2>{ar?"المنتج الجيد يجعل مهمة ما أسهل.":"Good software makes someone's day work better."}</h2><p>{ar?"حجز أسهل، معلومة أوضح، مهمة تأخذ وقت أقل. نربط قرارات التصميم والتنفيذ بما يهم الناس الذين سيستخدمون المنتج. وفهمنا للسوق السعودي يظهر في التجربة، من اللغة واتجاه القراءة إلى طريقة العمل.":"A simpler booking. Clearer information. A task that takes less time. We connect design and engineering decisions to the people who will use the product. Our understanding of Saudi Arabia shapes the experience, from language and reading direction to the way the work happens."}</p></section><section className="dir-principles dir-container">{principles.map(([title,body],i)=><article key={title}><span>0{i+1}</span><h2>{title}</h2><p>{body}</p></article>)}</section><section className="dir-people dir-container"><h2>{ar?"التوجه والتنفيذ.\nفي مكان واحد.":"Direction and delivery.\nIn one conversation."}</h2><div><article><span className="dir-person-mark" aria-hidden>AA</span><h3>{ar?"عبدالله السبيعي":"Abdullah Al Subaie"}</h3><p>{ar?"المؤسس والرئيس التنفيذي":"Founder & CEO"}</p><p className="dir-person-bio">{ar?"يقود توجه الاستوديو، وعلاقة العمل معك، وتحديد نطاق المشروع.":"Leads the studio’s direction, client relationships and project scope."}</p></article><article><span className="dir-person-mark" aria-hidden>MA</span><h3>{ar?"محمد عامر":"Mohammad Aamir"}</h3><p>{ar?"الرئيس التقني":"CTO"}</p><p className="dir-person-bio">{ar?"يقود التوجه التقني وهندسة البرمجيات وتحويل الخطة إلى منتج يعمل.":"Leads technical direction, software architecture and engineering delivery."}</p></article></div></section><SiteCTA locale={locale} base={base}/></>;
}
export async function SiteLegal({locale,base,kind}:{locale:Locale;base:string;kind:"privacy"|"terms"}) {
 const ar=locale==="ar",t=await getTranslations({locale,namespace:"Legal"});const sections=t.raw(`${kind}.sections`) as {heading:string;body:string}[];
 return <article className="dir-legal dir-container"><Link className="dir-breadcrumb" href={base || "/"}><span aria-hidden="true">←</span> {ar?"العودة للرئيسية":"Back to home"}</Link><h1>{t(`${kind}.title`)}</h1><p>{t("lastUpdated",{updated:t("updated")})}</p>{sections.map(s=><section key={s.heading}><h2>{s.heading}</h2><p>{s.body}</p></section>)}</article>;
}
