"use client";

import { Merged } from "@react-three/drei";
import { useFrame, type ThreeElements } from "@react-three/fiber";
import { createContext, useContext, useEffect, useMemo, useRef, type ReactNode } from "react";
import * as THREE from "three";
import { PixelBlastScreen } from "./PixelBlastScreen";
import { useComputersModel } from "./useComputersModel";

/*
Scene graph auto-generated by: npx gltfjsx computers.glb --transform --instance
The --instance flag detects repeated geometry and instances it, which is what
keeps a wall of ~90 monitors down to a handful of draw calls.

Model: "Old Computers" by Rafael Rodrigues (https://sketchfab.com/RafaelBR873D)
Source: https://sketchfab.com/3d-models/old-computers-7bb6e720499a467b8e0427451d180063
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)

CC-BY permits commercial use but *requires* visible attribution — this comment
does not satisfy it. The credit line rendered in the hero does. Do not ship this
scene without one.

Ported from the pmndrs example (github.com/pmndrs/examples/tree/main/examples/monitors)
to TypeScript and Next.js. Deviations from upstream:
  - the decorative bunny and its `@pmndrs/assets` download are dropped; its
    warm point light stays, now reading as spill from the centre screen
  - the text screens carry the Muse wordmark in brand orange
  - the one interactive screen runs the site's own PixelBlast shader instead of
    upstream's spinning cube — see PixelBlastScreen.tsx
  - screen scroll phases are seeded per-monitor rather than randomised during
    render, which upstream did on every frame
*/

/** The render-prop argument drei hands back from `Merged` — a component per
 *  instanced mesh, keyed by the names given in the `meshes` prop. */
type MergedInstances = Parameters<React.ComponentProps<typeof Merged>["children"]>[0];

const InstanceContext = createContext<MergedInstances | null>(null);

/**
 * A stand-in mesh for the LED spheres, carrying the GLTF's geometry but an
 * unlit, un-tone-mapped material — the LEDs get their colour written per
 * instance every frame and are meant to clip and bleed into the bloom pass.
 *
 * Upstream reassigned `nodes.Sphere.material` in place. That mutates the
 * cached GLTF, which drei shares across every consumer of the URL, and it does
 * it during render. Constructing a separate mesh keeps the loaded model
 * untouched and the render pure; `Merged` only ever reads `.geometry` and
 * `.material` off what it is given, so it cannot tell the difference.
 */
function buildLedMesh(source: THREE.Mesh): THREE.Mesh {
  const material = new THREE.MeshBasicMaterial();
  material.toneMapped = false;
  return new THREE.Mesh(source.geometry, material);
}

function useInstances(): MergedInstances {
  const instances = useContext(InstanceContext);
  if (!instances) throw new Error("<Computers> must be rendered inside <Instances>");
  return instances;
}

export function Instances({ children }: { children: ReactNode }) {
  const { nodes } = useComputersModel();
  const instances = useMemo(
    () => ({
      Object: nodes.Object_4,
      Object1: nodes.Object_16,
      Object3: nodes.Object_52,
      Object13: nodes.Object_172,
      Object14: nodes.Object_174,
      Object23: nodes.Object_22,
      Object24: nodes.Object_26,
      Object32: nodes.Object_178,
      Object36: nodes.Object_28,
      Object45: nodes.Object_206,
      Object46: nodes.Object_207,
      Object47: nodes.Object_215,
      Object48: nodes.Object_216,
      Sphere: buildLedMesh(nodes.Sphere as THREE.Mesh),
    }),
    [nodes],
  );
  return (
    <Merged castShadow receiveShadow meshes={instances}>
      {(merged) => <InstanceContext.Provider value={merged}>{children}</InstanceContext.Provider>}
    </Merged>
  );
}

export function Computers(props: ThreeElements["group"]) {
  const { meshes, materials } = useComputersModel();
  const i = useInstances();
  return (
    <group {...props} dispose={null}>
      <i.Object position={[0.16, 0.79, -1.97]} rotation={[-0.54, 0.93, -1.12]} scale={0.5} />
      <i.Object position={[-2.79, 0.27, 1.82]} rotation={[-1.44, 1.22, 1.43]} scale={0.5} />
      <i.Object position={[-5.6, 4.62, -0.03]} rotation={[-1.96, 0.16, 1.2]} scale={0.5} />
      <i.Object position={[2.62, 1.98, -2.47]} rotation={[-0.42, -0.7, -1.85]} scale={0.5} />
      <i.Object position={[4.6, 3.46, 1.19]} rotation={[-1.24, -0.72, 0.48]} scale={0.5} />
      <i.Object1 position={[0.63, 0, -3]} rotation={[0, 0.17, 0]} scale={1.52} />
      <i.Object1 position={[-2.36, 0.32, -2.02]} rotation={[0, 0.53, -Math.PI / 2]} scale={1.52} />
      <mesh castShadow receiveShadow geometry={meshes.Object_24.geometry} material={materials.Texture} position={[-2.42, 0.94, -2.25]} rotation={[0, 0.14, Math.PI / 2]} scale={-1.52} />
      <i.Object1 position={[-3.53, 0, 0.59]} rotation={[Math.PI, -1.09, Math.PI]} scale={1.52} />
      <i.Object1 position={[-3.53, 1.53, 0.59]} rotation={[0, 0.91, 0]} scale={1.52} />
      <i.Object1 position={[3.42, 0, 0]} rotation={[-Math.PI, 1.13, -Math.PI]} scale={1.52} />
      <i.Object1 position={[4.09, 2.18, 2.41]} rotation={[0, -1.55, 1.57]} scale={1.52} />
      <i.Object3 position={[4.31, 1.57, 2.34]} rotation={[0, -1.15, -Math.PI / 2]} scale={-1.52} />
      <i.Object3 position={[-3.79, 0, 1.66]} rotation={[Math.PI, -1.39, 0]} scale={-1.52} />
      <i.Object3 position={[-3.79, 1.53, 1.66]} rotation={[0, 1.22, -Math.PI]} scale={-1.52} />
      <i.Object1 position={[-3.69, 0, 2.59]} rotation={[0, -1.57, 0]} scale={1.52} />
      <i.Object1 position={[-5.36, 2.18, 0.81]} rotation={[0, 0.77, Math.PI / 2]} scale={1.52} />
      <i.Object3 position={[-5.56, 1.57, 0.69]} rotation={[0, 1.17, -Math.PI / 2]} scale={-1.52} />
      <i.Object1 position={[-5.47, 2.79, 0.74]} rotation={[Math.PI, -1.16, Math.PI / 2]} scale={1.52} />
      <i.Object3 position={[-5.29, 3.41, 0.89]} rotation={[Math.PI, -0.76, -Math.PI / 2]} scale={-1.52} />
      <i.Object1 position={[-5.28, 0, -2.33]} rotation={[0, 0.75, 0]} scale={1.52} />
      <i.Object1 position={[-5.49, 0, -1.38]} rotation={[Math.PI, -0.99, Math.PI]} scale={1.52} />
      <i.Object1 position={[-3.01, 0, -3.79]} rotation={[0, 0.6, 0]} scale={1.52} />
      <i.Object1 position={[-2.08, 0, -4.32]} rotation={[Math.PI, -0.6, Math.PI]} scale={1.52} />
      <i.Object1 position={[-1.02, 0, -4.49]} rotation={[0, 0.31, 0]} scale={1.52} />
      <i.Object1 position={[-5.31, 1.83, -1.41]} rotation={[0, 1.06, Math.PI / 2]} scale={1.52} />
      <i.Object1 position={[-4.18, 1.83, -3.06]} rotation={[-Math.PI, -0.46, -Math.PI / 2]} scale={1.52} />
      <i.Object1 position={[-1.76, 1.83, -3.6]} rotation={[0, -1.16, Math.PI / 2]} scale={1.52} />
      <i.Object1 position={[-0.25, 1.83, -5.54]} rotation={[0, 1.55, 1.57]} scale={1.52} />
      <i.Object1 position={[-5.28, 2.14, -2.33]} rotation={[Math.PI, -0.75, Math.PI]} scale={1.52} />
      <i.Object1 position={[-5.49, 2.14, -1.38]} rotation={[0, 0.99, 0]} scale={1.52} />
      <i.Object1 position={[-3.01, 2.14, -3.79]} rotation={[Math.PI, -0.6, Math.PI]} scale={1.52} />
      <i.Object1 position={[-2.08, 2.14, -4.32]} rotation={[0, 0.6, 0]} scale={1.52} />
      <i.Object1 position={[-1.02, 2.14, -4.49]} rotation={[Math.PI, -0.31, Math.PI]} scale={1.52} />
      <i.Object1 position={[-5.31, 3.98, -1.41]} rotation={[0, 1.06, Math.PI / 2]} scale={1.52} />
      <i.Object1 position={[-4.18, 3.98, -3.06]} rotation={[-Math.PI, -0.46, -Math.PI / 2]} scale={1.52} />
      <i.Object1 position={[-1.17, 3.98, -4.45]} rotation={[0, 0.17, Math.PI / 2]} scale={1.52} />
      <i.Object1 position={[-0.94, 3.98, -4.66]} rotation={[Math.PI, 0.02, -Math.PI / 2]} scale={1.52} />
      <mesh castShadow receiveShadow geometry={meshes.Object_140.geometry} material={materials.Texture} position={[5.53, 2.18, 0.17]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_144.geometry} material={materials.Texture} position={[5.74, 1.57, 0.05]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_148.geometry} material={materials.Texture} position={[5.65, 2.79, 0.11]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_152.geometry} material={materials.Texture} position={[5.46, 3.41, 0.26]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_156.geometry} material={materials.Texture} position={[4.86, 0, -2.54]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_160.geometry} material={materials.Texture} position={[5.06, 0, -1.6]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_164.geometry} material={materials.Texture} position={[2.59, 0, -4]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_168.geometry} material={materials.Texture} position={[1.66, 0, -4.54]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_170.geometry} material={materials.Texture} position={[0.59, 0, -4.7]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <i.Object13 position={[4.89, 1.83, -1.62]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <i.Object14 position={[3.75, 1.83, -3.28]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_176.geometry} material={materials.Texture} position={[1.33, 1.83, -3.82]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_180.geometry} material={materials.Texture} position={[4.86, 2.14, -2.54]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_184.geometry} material={materials.Texture} position={[5.06, 2.14, -1.6]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_188.geometry} material={materials.Texture} position={[2.59, 2.14, -4]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_192.geometry} material={materials.Texture} position={[1.66, 2.14, -4.54]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_194.geometry} material={materials.Texture} position={[0.59, 2.14, -4.7]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <i.Object13 position={[4.89, 3.98, -1.62]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <i.Object14 position={[3.75, 3.98, -3.28]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_200.geometry} material={materials.Texture} position={[0.75, 3.98, -4.66]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_18.geometry} material={materials.Texture} position={[-0.19, 0, -2.96]} rotation={[0, -0.06, 0]} scale={1.52} />
      <i.Object23 position={[-2.29, 1.56, -2.26]} rotation={[0, -0.005, -Math.PI / 2]} scale={1.52} />
      <i.Object24 position={[-2.19, 2.19, -1.87]} rotation={[0, 0.51, Math.PI / 2]} scale={-1.52} />
      <i.Object23 position={[-2.9, 0.3, -1.47]} rotation={[Math.PI, -1.35, Math.PI / 2]} scale={1.52} />
      <i.Object23 position={[3.22, 0, -0.8]} rotation={[0, -1.32, 0]} scale={1.52} />
      <i.Object23 position={[3.53, 1.83, 0.44]} rotation={[-Math.PI, 1.32, Math.PI / 2]} scale={1.52} />
      <i.Object23 position={[4.26, 0.94, 2.22]} rotation={[0, -1, Math.PI / 2]} scale={1.52} />
      <i.Object24 position={[3.87, 0.32, 2.35]} rotation={[0, -1.53, -1.57]} scale={-1.52} />
      <i.Object23 position={[-5.61, 0.94, 0.82]} rotation={[0, 1.32, 1.57]} scale={1.52} />
      <i.Object24 position={[-5.26, 0.32, 1.01]} rotation={[0, 0.79, -Math.PI / 2]} scale={-1.52} />
      <i.Object23 position={[-5.39, 4.03, 0.99]} rotation={[Math.PI, -0.61, Math.PI / 2]} scale={1.52} />
      <i.Object24 position={[-5.7, 4.66, 0.72]} rotation={[Math.PI, -1.13, -Math.PI / 2]} scale={-1.52} />
      <i.Object23 position={[-5.95, 0, -0.64]} rotation={[0, 0.95, 0]} scale={1.52} />
      <i.Object23 position={[-4.48, 0, -2.75]} rotation={[Math.PI, -0.57, Math.PI]} scale={1.52} />
      <i.Object23 position={[-3.72, 0, -2.89]} rotation={[0, 0.64, 0]} scale={1.52} />
      <i.Object23 position={[-0.08, 0, -5.03]} rotation={[Math.PI, -0.04, Math.PI]} scale={1.52} />
      <i.Object24 position={[-4.19, 1.84, -2.77]} rotation={[Math.PI, -0.66, -Math.PI / 2]} scale={-1.52} />
      <i.Object23 position={[-5.95, 2.14, -0.64]} rotation={[Math.PI, -0.95, Math.PI]} scale={1.52} />
      <i.Object23 position={[-4.48, 2.14, -2.75]} rotation={[0, 0.57, 0]} scale={1.52} />
      <i.Object23 position={[-3.73, 2.14, -3.1]} rotation={[Math.PI, -0.64, Math.PI]} scale={1.52} />
      <i.Object23 position={[-0.08, 2.14, -5.03]} rotation={[0, 0.04, 0]} scale={1.52} />
      <i.Object24 position={[-4.19, 3.98, -2.77]} rotation={[Math.PI, -0.66, -Math.PI / 2]} scale={-1.52} />
      <mesh castShadow receiveShadow geometry={meshes.Object_142.geometry} material={materials.Texture} position={[5.79, 0.94, 0.18]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_146.geometry} material={materials.Texture} position={[5.43, 0.32, 0.37]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_150.geometry} material={materials.Texture} position={[5.56, 4.03, 0.35]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_154.geometry} material={materials.Texture} position={[5.87, 4.66, 0.08]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_158.geometry} material={materials.Texture} position={[5.53, 0, -0.85]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_162.geometry} material={materials.Texture} position={[4.05, 0, -2.96]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_166.geometry} material={materials.Texture} position={[3.29, 0, -3.1]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <i.Object32 position={[3.77, 1.84, -2.98]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_182.geometry} material={materials.Texture} position={[5.53, 2.14, -0.85]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_186.geometry} material={materials.Texture} position={[4.05, 2.14, -2.96]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh castShadow receiveShadow geometry={meshes.Object_190.geometry} material={materials.Texture} position={[3.3, 2.14, -3.31]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <i.Object32 position={[3.77, 3.98, -2.98]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <i.Object36 position={[0.35, 2.35, -3.34]} rotation={[-0.26, 0, 0]} />
      <i.Object36 position={[0.18, 2.8, -2.85]} rotation={[0.09, 0.15, -0.005]} />
      <i.Object36 position={[1.89, 0, -1.94]} rotation={[0, -0.44, 0]} scale={[1.5, 1, 1.5]} />
      <i.Object36 position={[1.86, 1.61, -1.81]} rotation={[0, -Math.PI / 3, 0]} />
      <i.Object36 position={[3.95, 2.49, 1.61]} rotation={[0, -Math.PI / 3, 0]} />
      <i.Object36 position={[-1.1, 4.29, -4.43]} rotation={[0, 0.36, 0]} />
      <i.Object36 position={[-5.25, 4.29, -1.47]} rotation={[0, 1.25, 0]} />
      <mesh castShadow receiveShadow geometry={meshes.Object_204.geometry} material={materials.Texture} position={[3.2, 4.29, -3.09]} rotation={[-Math.PI, 0.56, 0]} scale={-1} />

      {/* The one screen you can touch — front and centre, facing the camera. */}
      <PixelBlastScreen frame="Object_206" panel="Object_207" position={[0.27, 1.53, -2.61]} />

      <ScreenText seed={0} frame="Object_209" panel="Object_210" position={[-1.43, 2.5, -1.8]} rotation={[0, 1, 0]} />
      <ScreenText seed={1} invert frame="Object_212" panel="Object_213" position={[-2.73, 0.63, -0.52]} rotation={[0, 1.09, 0]} />
      <ScreenText seed={2} invert frame="Object_215" panel="Object_216" position={[1.84, 0.38, -1.77]} rotation={[0, -Math.PI / 9, 0]} />
      <ScreenText seed={3} invert frame="Object_218" panel="Object_219" position={[3.11, 2.15, -0.18]} rotation={[0, -0.79, 0]} scale={0.81} />
      <ScreenText seed={4} frame="Object_221" panel="Object_222" position={[-3.42, 3.06, 1.3]} rotation={[0, 1.22, 0]} scale={0.9} />
      <ScreenText seed={5} invert frame="Object_224" panel="Object_225" position={[-3.9, 4.29, -2.64]} rotation={[0, 0.54, 0]} />
      <ScreenText seed={6} frame="Object_227" panel="Object_228" position={[0.96, 4.28, -4.2]} rotation={[0, -0.65, 0]} />
      <ScreenText seed={7} frame="Object_230" panel="Object_231" position={[4.68, 4.29, -1.56]} rotation={[0, -Math.PI / 3, 0]} />

      <Leds />
    </group>
  );
}

/** Brand orange on black, or its inverse — the wall alternates between the two. */
const SCREEN_ORANGE = "#FE4701";
const SCREEN_BLACK = "#000000";
const WORDMARK = "Muse.";

/**
 * Each text screen is a 2D canvas painted once and scrolled by animating the
 * texture offset, not a second 3D scene rendered into a framebuffer.
 *
 * Upstream drew these with drei's <Text>, which is troika-three-text, which
 * builds its glyph-shaping worker by inlining source into a Blob and then
 * calling `importScripts` on more Blob URLs. Under this site's CSP that fails,
 * and it does not fail gracefully — the worker rejects, the exception escapes
 * during render, and the entire react-three-fiber tree unmounts, leaving a
 * black canvas. Allowing `blob:` in `script-src` would fix it by weakening the
 * one directive worth keeping tight.
 *
 * A canvas texture avoids the question and is strictly cheaper anyway: it
 * drops eight live render targets from the frame, needs no font file shipped
 * to `public/`, and — because it paints with the real `--font-space-grotesk`
 * family — puts the brand face on the screens instead of upstream's Inter.
 */
const WORDMARK_TEXTURE_SIZE = 256;

/** The next/font family name, read off the CSS variable the layout sets. */
function brandFontStack(): string {
  const source = document.body ?? document.documentElement;
  const family = getComputedStyle(source).getPropertyValue("--font-space-grotesk").trim();
  return family ? `${family}, sans-serif` : "sans-serif";
}

function paintWordmark(canvas: HTMLCanvasElement, invert: boolean) {
  const ctx = canvas.getContext("2d");
  if (!ctx) return;
  const size = canvas.width;
  ctx.fillStyle = invert ? SCREEN_BLACK : SCREEN_ORANGE;
  ctx.fillRect(0, 0, size, size);
  ctx.fillStyle = invert ? SCREEN_ORANGE : SCREEN_BLACK;
  ctx.font = `700 ${Math.round(size * 0.26)}px ${brandFontStack()}`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(WORDMARK, size / 2, size / 2);
}

/**
 * Builds the texture into a ref and hangs it on the material imperatively,
 * rather than creating it in a `useMemo` and passing it as a `map` prop.
 *
 * three.js objects are mutable by design and this one is mutated constantly —
 * repainted when the webfont lands, scrolled every frame — but React Compiler
 * freezes any value that reaches JSX, so a texture passed as a prop may not
 * legally be touched again. Refs are the supported escape hatch for exactly
 * this: mutable state the renderer owns and React does not.
 */
function useWordmarkTexture(
  materialRef: React.RefObject<THREE.MeshBasicMaterial | null>,
  invert: boolean,
) {
  const textureRef = useRef<THREE.CanvasTexture | null>(null);

  useEffect(() => {
    const canvas = document.createElement("canvas");
    canvas.width = WORDMARK_TEXTURE_SIZE;
    canvas.height = WORDMARK_TEXTURE_SIZE;

    const texture = new THREE.CanvasTexture(canvas);
    // Horizontal repeat is what makes the offset scroll wrap seamlessly; the
    // vertical axis never moves, so it clamps.
    texture.wrapS = THREE.RepeatWrapping;
    texture.wrapT = THREE.ClampToEdgeWrapping;
    texture.colorSpace = THREE.SRGBColorSpace;
    texture.anisotropy = 8;
    textureRef.current = texture;

    const material = materialRef.current;
    if (material) {
      material.map = texture;
      material.needsUpdate = true;
    }

    const draw = () => {
      paintWordmark(canvas, invert);
      texture.needsUpdate = true;
    };
    draw();
    // next/font resolves Space Grotesk asynchronously, so the first paint can
    // land on the fallback face. Repaint once the real one is in.
    let cancelled = false;
    void document.fonts.ready.then(() => {
      if (!cancelled) draw();
    });

    return () => {
      cancelled = true;
      textureRef.current = null;
      texture.dispose();
    };
  }, [materialRef, invert]);

  return textureRef;
}

/** How much of the texture scrolls past per second. Slow — it should read as
 *  ambient movement on a wall, not as something asking to be read. */
const SCROLL_RATE = 0.05;

type ScreenTextProps = Omit<ThreeElements["group"], "children"> & {
  frame: string;
  panel: string;
  invert?: boolean;
  /** Fixes this screen's scroll phase. Upstream drew a fresh `Math.random()`
   *  on every render, so the phase jumped whenever React re-rendered; a stable
   *  per-screen seed staggers the wall without that. */
  seed: number;
};

function ScreenText({ invert = false, seed, frame, panel, ...props }: ScreenTextProps) {
  const { meshes, materials } = useComputersModel();
  const materialRef = useRef<THREE.MeshBasicMaterial>(null);
  const textureRef = useWordmarkTexture(materialRef, invert);

  useFrame((state) => {
    const texture = textureRef.current;
    if (!texture) return;
    texture.offset.x = (seed * 0.137 + state.clock.elapsedTime * SCROLL_RATE) % 1;
  });

  return (
    <group {...props}>
      <mesh castShadow receiveShadow geometry={meshes[frame].geometry} material={materials.Texture} />
      {/* `toneMapped={false}` keeps the screen out of the renderer's tone curve
          so it reads as emitting, and feeds the bloom pass cleanly. The map is
          attached by useWordmarkTexture once the canvas exists. */}
      <mesh geometry={meshes[panel].geometry}>
        <meshBasicMaterial ref={materialRef} toneMapped={false} />
      </mesh>
    </group>
  );
}

/** Flashing status LEDs. The colour is driven per-instance every frame, which
 *  is why they are `MeshBasicMaterial` with tone mapping off — they are meant
 *  to clip and bleed into the bloom pass. */
function Leds() {
  const ref = useRef<THREE.Group>(null);
  const i = useInstances();

  useFrame((state) => {
    if (!ref.current) return;
    for (const child of ref.current.children) {
      const led = child as THREE.Object3D & { color: THREE.Color };
      if (!led.color) continue;
      const rand = Math.abs(2 + led.position.x);
      const t = Math.round((1 + Math.sin(rand * 10000 + state.clock.elapsedTime * rand)) / 2);
      led.color.setRGB(0, t * 1.1, t);
    }
  });

  return (
    <group ref={ref}>
      <i.Sphere position={[-0.41, 1.1, -2.21]} scale={0.005} color={[1, 2, 1]} />
      <i.Sphere position={[0.59, 1.32, -2.22]} scale={0.005} color={[1, 2, 1]} />
      <i.Sphere position={[1.77, 1.91, -1.17]} scale={0.005} color={[1, 2, 1]} />
      <i.Sphere position={[2.44, 1.1, -0.79]} scale={0.005} color={[1, 2, 1]} />
      <i.Sphere position={[4.87, 3.8, -0.1]} scale={0.005} color={[1, 2, 1]} />
      <i.Sphere position={[1.93, 3.8, -3.69]} scale={0.005} color={[1, 2, 1]} />
      <i.Sphere position={[-2.35, 3.8, -3.48]} scale={0.005} color={[1, 2, 1]} />
      <i.Sphere position={[-4.71, 4.59, -1.81]} scale={0.005} color={[1, 2, 1]} />
      <i.Sphere position={[-3.03, 2.85, 1.19]} scale={0.005} color={[1, 2, 1]} />
      <i.Sphere position={[-1.21, 1.73, -1.49]} scale={0.005} color={[1, 2, 1]} />
    </group>
  );
}
