import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import AxeBuilder from '@axe-core/playwright';
import {launchBrowser} from './browser-runtime.mjs';
const base=process.env.MUSE_TEST_URL||'http://127.0.0.1:3106';
const out='test-results/inquiry';mkdirSync(out,{recursive:true});const browser=await launchBrowser();const results=[];
async function setup(width=390){const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'});const page=await context.newPage();const errors=[],posts=[];page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',r=>{if(!['GET','HEAD','OPTIONS'].includes(r.request().method())){posts.push(r.request().url());return r.abort();}return r.continue();});await page.addInitScript(()=>{window.handoffs=[];window.copied='';Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copied=text}}});document.addEventListener('click',e=>{const a=e.target.closest?.('a');if(a?.href.startsWith('mailto:')){e.preventDefault();window.handoffs.push(a.href)}},true)});return {context,page,errors,posts};}
async function step(page,n){await page.locator(`.inquiry-layout[data-ready=true][data-step="${n}"]`).waitFor();}
async function next(page){await page.locator('.form-actions>.studio-button').click();}
try{
 if(!process.argv.includes('--edges-only'))for(const locale of ['en','ar'])for(const width of [320,390,1440]){
  const {context,page,errors,posts}=await setup(width);await page.goto(`${base}/${locale}`);await page.locator('.mx-email-cta a').click();await page.waitForURL(`${base}/${locale}/start`);await step(page,1);
  await next(page);assert(await page.locator('#intent-error').isVisible());await page.locator('.intent-options label').first().click();await next(page);await step(page,2);
  const note=locale==='ar'?'نحتاج منصة للحجز & إدارة العملاء. التفاصيل: A+B?':'A booking app & customer dashboard. Details: A+B?';
  await page.locator('#description').fill(note);await page.locator('#timeline').selectOption('1-3 months');await page.locator('.inquiry-panel').screenshot({path:`${out}/${locale}-${width}-idea.png`});await next(page);await step(page,3);
  await next(page);assert(await page.locator('#firstName-error').isVisible());assert.equal(await page.locator('#firstName').evaluate(e=>e===document.activeElement),true);
  await page.locator('#firstName').fill(locale==='ar'?'عميل تجريبي':'Test Client');await page.locator('#email').fill('invalid');await next(page);assert(await page.locator('#email-error').isVisible());await page.locator('#email').fill('client@example.com');await page.locator('#company').fill('Studio & Partners');await page.locator('.contact-preference label').last().click();await page.locator('#phone').fill('12');await next(page);assert(await page.locator('#phone-error').isVisible());await page.locator('#phone').fill(locale==='ar'?'٠٥٩٢٧٣١٠٤٠':'0592731040');
  await page.locator('.inquiry-review summary').click();assert((await page.locator('.inquiry-review dd').last().innerText()).includes(note));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:`${out}/${locale}-${width}-details.png`});
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(axe.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),[]);
  await next(page);await step(page,4);const handoffs=await page.evaluate(()=>window.handoffs);assert.equal(handoffs.length,1);const email=new URL(handoffs[0]);assert.equal(email.pathname,'abdullah@muse.sa');const body=email.searchParams.get('body');for(const value of [note,'client@example.com','Studio & Partners','0592731040'])assert(body.includes(value),value);assert(email.searchParams.get('subject').includes(locale==='ar'?'عميل تجريبي':'Test Client'));
  await page.locator('.inquiry-copy-actions button').first().click();assert((await page.evaluate(()=>window.copied)).includes(body));
  await page.evaluate(()=>{navigator.clipboard.writeText=async()=>{throw new Error('denied')}});await page.locator('.inquiry-copy-actions button').first().click();assert.equal(await page.locator('#prepared-message').evaluate(e=>e.selectionEnd-e.selectionStart),await page.locator('#prepared-message').evaluate(e=>e.value.length));
  await page.locator('.inquiry-handoff').screenshot({path:`${out}/${locale}-${width}-email.png`});await page.locator('.inquiry-copy-actions button').last().click();await step(page,3);assert.equal(await page.locator('#email').inputValue(),'client@example.com');
  await page.reload();await page.locator('.draft-notice').waitFor();await page.locator('.draft-notice button').first().click();await step(page,3);assert.equal(await page.locator('#email').inputValue(),'client@example.com');assert.deepEqual(errors,[]);assert.deepEqual(posts,[]);
  results.push({locale,width,pass:true});console.log(`PASS ${locale} ${width}: entry, steps, errors, fields, email encoding, copy/fallback, edit, restore, accessibility, no submissions`);await context.close();
 }
 const {context,page,errors,posts}=await setup();await page.goto(`${base}/en/start?intent=ai`);await step(page,2);const long='تفاصيل المشروع & المزيد؟ '.repeat(160).slice(0,4000);await page.locator('#description').fill(long);await next(page);await page.locator('#firstName').fill('Long note');await page.locator('#email').fill('long@example.com');await next(page);await step(page,4);assert((await page.locator('#prepared-message').inputValue()).includes(long.trim()));assert(new URL((await page.evaluate(()=>window.handoffs))[0]).searchParams.get('body').includes(long.trim()));assert(await page.getByText('Long messages can be cut off',{exact:false}).isVisible());
 await page.goto(`${base}/ar/start?intent=ai`);await page.locator('.draft-notice button').first().click();await step(page,3);assert.equal(await page.locator('#firstName').inputValue(),'Long note');await page.goBack();
 await page.evaluate(()=>sessionStorage.setItem('muse-email-enquiry-v1','{broken'));await page.goto(`${base}/en/start?intent=bogus`);await step(page,1);assert.equal(await page.locator('.draft-notice').count(),0);assert.deepEqual(errors,[]);assert.deepEqual(posts,[]);await context.close();
 const unavailable=await setup();await unavailable.page.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new Error('blocked')};Storage.prototype.setItem=()=>{throw new Error('blocked')}});await unavailable.page.goto(`${base}/en/start`);await step(unavailable.page,1);assert(await unavailable.page.getByText('Draft saving is unavailable.',{exact:false}).isVisible());await unavailable.context.close();
 console.log('PASS long multilingual note without truncation, cross-locale restore, invalid intent, corrupt/blocked storage');
}finally{writeFileSync(`${out}/${process.argv.includes('--edges-only')?'edge-results':'results'}.json`,JSON.stringify(results,null,2));await browser.close();}
